name: Demo
main: edu.unca.nrodrigu.Demo.Demo
version: 0.4
author: Nick Rodriguez
description: Demo plugin
commands:
  cake:
    description: give the player a block of cake
    usage: /<command>
    permission: demo.cake
  pit:
    description: transforms next 10 blocks below player to air
    usage: /<command>
    permission: demo.pit
  midas:
    description: transform the block player is standing on to gold
    usage: /<command>
    permission: demo.midas
  zdefend:
    description: launch a horde of zombies - defend yourself with a diamond sword
    usage: /<command>
    permission: demo.zdefend
  pitplayer:
    description: create a pit under another player
    usage: /<command> <player>
    permission: demo.pitplayer
permissions:
  demo.*:
    description: permissions of all demo plugin commands
    default: true
    children:
      demo.pitplayer:
        default: op
